--------------------------------------------------------
--  File created - Wednesday-November-08-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXFARMS
--------------------------------------------------------

  CREATE TABLE "XXFF"."XXFARMS" 
   (	"C_R" NUMBER(4,0), 
	"C_X" NUMBER(3,0), 
	"C_Y" NUMBER(3,0), 
	"NICK_NAME" VARCHAR2(400 BYTE), 
	"READY_TO_GUILD" NUMBER(1,0), 
	"OWNER_NAME" VARCHAR2(400 BYTE), 
	"COMMENTARY" VARCHAR2(4000 BYTE), 
	"RSS_STONE" NUMBER(1,0), 
	"RSS_ENERGY" NUMBER(1,0), 
	"RSS_METAL" NUMBER(1,0), 
	"RSS_GIL" NUMBER(1,0), 
	"RSS_FOOD" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5221302426447754" ;
--------------------------------------------------------
--  DDL for Index XXFARMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXFF"."XXFARMS_PK" ON "XXFF"."XXFARMS" ("C_R", "C_X", "C_Y") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5221302426447754" ;
--------------------------------------------------------
--  Constraints for Table XXFARMS
--------------------------------------------------------

  ALTER TABLE "XXFF"."XXFARMS" ADD CONSTRAINT "XXFARMS_PK" PRIMARY KEY ("C_R", "C_X", "C_Y")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5221302426447754"  ENABLE;
  ALTER TABLE "XXFF"."XXFARMS" MODIFY ("READY_TO_GUILD" NOT NULL ENABLE);
  ALTER TABLE "XXFF"."XXFARMS" MODIFY ("NICK_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXFF"."XXFARMS" MODIFY ("C_Y" NOT NULL ENABLE);
  ALTER TABLE "XXFF"."XXFARMS" MODIFY ("C_X" NOT NULL ENABLE);
  ALTER TABLE "XXFF"."XXFARMS" MODIFY ("C_R" NOT NULL ENABLE);
