--------------------------------------------------------
--  File created - Wednesday-November-08-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXUSERS
--------------------------------------------------------

  CREATE TABLE "XXFF"."XXUSERS" 
   (	"ID" NUMBER(6,0), 
	"USERNAME" VARCHAR2(16 BYTE), 
	"PASSWORD" VARCHAR2(64 BYTE), 
	"STATUS" VARCHAR2(16 BYTE), 
	"ROLE" VARCHAR2(16 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5221302426447754" ;
--------------------------------------------------------
--  DDL for Index XXFF_USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXFF"."XXFF_USERS_PK" ON "XXFF"."XXUSERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5221302426447754" ;
--------------------------------------------------------
--  DDL for Index XXFF_USERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXFF"."XXFF_USERS_UK1" ON "XXFF"."XXUSERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5221302426447754" ;
--------------------------------------------------------
--  DDL for Trigger BI_XXFF_USERS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "XXFF"."BI_XXFF_USERS" 
  before insert on "XXUSERS"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "XXFF_USERS_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER "XXFF"."BI_XXFF_USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table XXUSERS
--------------------------------------------------------

  ALTER TABLE "XXFF"."XXUSERS" ADD CONSTRAINT "XXFF_USERS_CHEK_STATUS" CHECK ( "STATUS" IN ('OPEN','CLOSED','PENDING')) ENABLE;
  ALTER TABLE "XXFF"."XXUSERS" ADD CONSTRAINT "XXFF_USERS_CHEK_ROLE" CHECK (ROLE IN ('ADMIN','USER','VIEWER')) ENABLE;
  ALTER TABLE "XXFF"."XXUSERS" ADD CONSTRAINT "XXFF_USERS_CHEK_DATES" CHECK (START_DATE < END_DATE) ENABLE;
  ALTER TABLE "XXFF"."XXUSERS" ADD CONSTRAINT "XXFF_USERS_UK1" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5221302426447754"  ENABLE;
  ALTER TABLE "XXFF"."XXUSERS" ADD CONSTRAINT "XXFF_USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5221302426447754"  ENABLE;
  ALTER TABLE "XXFF"."XXUSERS" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXFF"."XXUSERS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXFF"."XXUSERS" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "XXFF"."XXUSERS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXFF"."XXUSERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "XXFF"."XXUSERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "XXFF"."XXUSERS" MODIFY ("ID" NOT NULL ENABLE);
